<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RolloutLoud.Platform.Unix</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RolloutLoud.Core\RolloutLoud.Core.csproj" />
  </ItemGroup>

</Project>
