<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>RolloutLoud.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>RolloutLoud</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RolloutLoud.Core\RolloutLoud.Core.csproj" />
    <ProjectReference Include="..\RolloutLoud.Platform.Unix\RolloutLoud.Platform.Unix.csproj" />
    <ProjectReference Include="..\RolloutLoud.Platform.Windows\RolloutLoud.Platform.Windows.csproj" />
  </ItemGroup>

</Project>
